version: "3.8"
services:
  web:
    build: ./frontend
    image: webapp
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - frontend
  api:
    build: ./api
    image: wepapi
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - backend
     - frontend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks: 
     - backend

networks:
  backend:
  frontend:

volumes: 
  mongodb_data:
